// Original audio synthesized at runtime; no recordings or third-party sound assets.
export class AudioEngine {
  constructor(){this.enabled=true;this.context=null;this.engine=null;}
  async unlock(){if(!this.context){this.context=new(window.AudioContext||window.webkitAudioContext)();this.master=this.context.createGain();this.master.gain.value=.18;this.master.connect(this.context.destination);this.engine=this.context.createOscillator();this.engine.type='triangle';this.engineGain=this.context.createGain();this.engineGain.gain.value=0;this.engine.connect(this.engineGain).connect(this.master);this.engine.start();}if(this.context.state==='suspended')await this.context.resume();}
  toggle(){this.enabled=!this.enabled;if(this.master)this.master.gain.setTargetAtTime(this.enabled?.18:0,this.context.currentTime,.05);return this.enabled;}
  tone(frequency,duration=.15,type='sine',gain=.3){if(!this.context||!this.enabled)return;const t=this.context.currentTime,o=this.context.createOscillator(),g=this.context.createGain();o.type=type;o.frequency.setValueAtTime(frequency,t);o.frequency.exponentialRampToValueAtTime(frequency*.65,t+duration);g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(this.master);o.start(t);o.stop(t+duration);o.onended=()=>{o.disconnect();g.disconnect();};}
  event(name){if(name==='go')this.tone(680,.4);else if(name==='finish'){[0,120,240].forEach((delay,i)=>setTimeout(()=>this.tone(420+i*140,.35),delay));}else if(name==='item'||name==='gate')this.tone(960,.22);else if(name==='driftBoost')this.tone(240,.4,'sawtooth',.11);else if(name==='recover')this.tone(140,.3);else this.tone(460,.18);}
  update(game){if(!this.context)return;const p=game.racers[0],running=game.state==='racing'&&!p.falling;this.engine.frequency.setTargetAtTime(45+Math.abs(p.speed)*2.8,this.context.currentTime,.12);this.engineGain.gain.setTargetAtTime(running?.035+Math.abs(p.speed)*.001:0,this.context.currentTime,.15);}
}
